# 可以push到github上，通过colab打开

In [29]:
import pandas as pd
import csv

In [34]:
raw_csv_path = './datasets/YearPredictionMSD.csv'
title_csv_path = './datasets/YearPredictionMSD.csv'
test_csv_path = './datasets/test.csv'

In [25]:
header_list = ['Year']
for i in range(1,91):
    header_list.append('arrt' + str(i))
print(header_list)

['Year', 'arrt1', 'arrt2', 'arrt3', 'arrt4', 'arrt5', 'arrt6', 'arrt7', 'arrt8', 'arrt9', 'arrt10', 'arrt11', 'arrt12', 'arrt13', 'arrt14', 'arrt15', 'arrt16', 'arrt17', 'arrt18', 'arrt19', 'arrt20', 'arrt21', 'arrt22', 'arrt23', 'arrt24', 'arrt25', 'arrt26', 'arrt27', 'arrt28', 'arrt29', 'arrt30', 'arrt31', 'arrt32', 'arrt33', 'arrt34', 'arrt35', 'arrt36', 'arrt37', 'arrt38', 'arrt39', 'arrt40', 'arrt41', 'arrt42', 'arrt43', 'arrt44', 'arrt45', 'arrt46', 'arrt47', 'arrt48', 'arrt49', 'arrt50', 'arrt51', 'arrt52', 'arrt53', 'arrt54', 'arrt55', 'arrt56', 'arrt57', 'arrt58', 'arrt59', 'arrt60', 'arrt61', 'arrt62', 'arrt63', 'arrt64', 'arrt65', 'arrt66', 'arrt67', 'arrt68', 'arrt69', 'arrt70', 'arrt71', 'arrt72', 'arrt73', 'arrt74', 'arrt75', 'arrt76', 'arrt77', 'arrt78', 'arrt79', 'arrt80', 'arrt81', 'arrt82', 'arrt83', 'arrt84', 'arrt85', 'arrt86', 'arrt87', 'arrt88', 'arrt89', 'arrt90']

In [20]:
"""with open(csv_path, 'r', newline='') as csv_in_file:
    with open(csv_path, 'w', newline='') as csv_out_file:
        filereader = csv.reader(csv_in_file)
        filewriter = csv.writer(csv_out_file)
        filewriter.writerow(header_list)
        for row in filereader:
            filewriter.writerow(row)"""

In [26]:
with open(raw_csv_path, 'r+', encoding='utf-8') as f:
    content = f.read()
    f.seek(0, 0)
    #mid, text, source, uid
    text = 'mid' + ',' + 'text' + ',' + 'source' + ',' + 'uid'
    f.write(text + '\n' + content)

In [35]:
data = pd.read_csv(test_csv_path,nrows =5)
data

,2001,49.94357,21.47114,73.07750,8.74861,-17.40628,-13.09905,-25.01202,-12.23257,7.83089,...,13.01620,-54.40548,58.99367,15.37344,1.11144,-23.08793,68.40795,-1.82223,-27.46348,2.26327\n
0,2001,48.73215,18.42930,70.32679,12.94636,-10.32437,-24.83777,8.76630,-0.92019,18.76548,...,5.66812,-19.68073,33.04964,42.87836,-9.90378,-32.22788,70.49388,12.04941,58.43453,26.92061
1,2001,50.95714,31.85602,55.81851,13.41693,-6.57898,-18.54940,-3.27872,-2.35035,16.07017,...,3.03800,26.05866,-50.92779,10.93792,-0.07568,43.20130,-115.00698,-0.05859,39.67068,-0.66345
2,2001,48.24750,-1.89837,36.29772,2.58776,0.97170,-26.21683,5.05097,-10.34124,3.55005,...,34.57337,-171.70734,-16.96705,-46.67617,-12.51516,82.58061,-72.08993,9.90558,199.62971,18.85382
3,2001,50.97020,42.20998,67.09964,8.46791,-15.85279,-16.81409,-12.48207,-9.37636,12.63699,...,9.92661,-55.95724,64.92712,-17.72522,-1.49237,-7.50035,51.76631,7.88713,55.66926,28.74903
4,2001,50.54767,0.31568,92.35066,22.38696,-25.51870,-19.04928,20.67345,-5.19943,3.63566,...,6.59753,-50.69577,26.02574,18.94430,-0.33730,6.09352,35.18381,5.00283,-11.02257,0.02263